# Generated by Django 5.1.3 on 2024-12-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_lisitng'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisitng',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lisitng',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
