# Generated by Django 5.1.3 on 2024-12-25 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_lisitng_bids_comment_lisitng_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisitng',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
