# Generated by Django 5.1.3 on 2024-12-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_lisitng_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lisitng',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='lisitng',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='lisitng',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
