# Generated by Django 5.1.3 on 2024-12-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_lisitng_bids_alter_lisitng_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisitng',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
