# Generated by Django 5.1.3 on 2024-12-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_lisitng_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lisitng',
            new_name='Listing',
        ),
    ]
