# Generated by Django 5.1.3 on 2024-12-26 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_lisitng_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='watch_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
